services:
  web:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: ${DOCKER_NAME}_app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./docker/apache2/sites-available:/etc/apache2/sites-available:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./service:/var/www/html
    ports:
      - 8142:80
    networks:
      - aesatao

  mysql-db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=xgJUIC2HRP1Ehu1Ljqvclr67DWAnile26fRF8EXl9OBns6H2jAeAW0gRAMONxpYB
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=I3wM2Q5kJZkSsIvYdmZJcoOJyTd10aRcnWcw8kKHKBPbzyXqN58vdbAmu4ECraQM
    ports:
      - '3376:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql:rw
    command: ['--mysql-native-password=ON']
    container_name: ${DOCKER_NAME}_db
    networks:
      - aesatao

networks:
  aesatao: