<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-06-04T13:28:47+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'UTC',
];
