<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-06-05T13:53:13+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      file_chooser.default_tab
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'pt_PT',
    'version_installed' => '9.4.1',
    'version_db_installed' => '20250227155410',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1749043726,
        'latest_version' => '9.4.1',
    ],
    'email' => [
        'default' => [
            'address' => 'pedro@nitrogenio.net',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
    'seo' => [
        'redirect_to_canonical_url' => false,
        'url_rewriting' => true,
    ],
    'file_chooser' => [
        'default_tab' => 'recent_uploads',
    ],
];
